import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />

				<div
					style={{
						width: "100%",
						height: "100%",
						backgroundColor: "#F2F3F6",
					}}
				>
					<div
						style={{
							width: "1050px",
							marginLeft: "auto",
							marginRight: "auto",
						}}
					>
						<div style={{ height: "40px" }}>მთავარი</div>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
