import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import "../public/fonts/stylesheet.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Header />

				<div className="w-full h-full bg-[#F2F3F6]">
					<div className="max-w-full mx-auto w-[1050px] flex flex-col">
						<div className="flex items-start px-4 lg:h-10">მთავარი</div>
						<div className="max-w-full mx-auto w-[1050px] flex flex-col items-center">
							<div className="text-center">{children}</div>
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
